### ISSUE TITLE
Node-RED stops when receiving request

### ISSUE THREAD

**Issue by rons4** [w35l3y/node-red-contrib-localtunnel#2] opened 2023-06-12 08:42 UTC
This is a very helpful node indeed. However, whenever a request is received it causes Node-RED to stop:

[error] TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string or an instance of Buffer or URL. Received undefined
    at Object.openSync (node:fs:592:10)
    at Object.readFileSync (node:fs:468:35)
    at getLocalCertOpts (/usr/local/lib/node_modules/node-red-contrib-localtunnel/node_modules/localtunnel/lib/TunnelCluster.js:79:24)
    at connLocal (/usr/local/lib/node_modules/node-red-contrib-localtunnel/node_modules/localtunnel/lib/TunnelCluster.js:86:62)
    at Socket.<anonymous> (/usr/local/lib/node_modules/node-red-contrib-localtunnel/node_modules/localtunnel/lib/TunnelCluster.js:149:7)
    at Object.onceWrapper (node:events:627:28)
    at Socket.emit (node:events:525:35)
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1466:10)

**Comment by w35l3y** [comment] 2023-06-12 09:14
You probably didn't inform certificate files (server.cer, server.key and ca.cer)
Make sure to unckeck "HTTPS" if you want to keep these fields in blank.

This is a duplicate of https://github.com/w35l3y/node-red-contrib-localtunnel/issues/1#issuecomment-955682934

**Closed as completed** 2023-06-12 09:23 UTC

**Comment by rons4** [comment] 2023-06-12 11:05
Thanks a lot. Sorry, I did not check the other issue.
